name: UISamples
options:
  bundleIdPrefix: com.gmail-yoshiki.tx
  developmentLanguage: ja
packages:
  realm-cocoa:
    url: https://github.com/realm/realm-cocoa.git
    version: 10.20.0
targets:
  UISamples:
    type: application
    platform: iOS
    deploymentTarget: "14.5"
    sources: [UISamples]
    preBuildScripts:
      - script: xcrun --sdk macosx mint run swiftgen
        name: Generate resources with SwiftGen
    dependencies:
      - package: realm-cocoa
        product: Realm
      - package: realm-cocoa
        product: RealmSwift
  UISamplesTests:
    type: bundle.unit-test
    platform: iOS
    sources: [UISamplesTests]
    dependencies:
      - target: UISamples
  UISamplesUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [UISamplesUITests]
    dependencies:
      - target: UISamples
schemes:
  UISamples:
    build:
      targets:
        UISamples: all
    run:
      config: Debug
